name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main # Change this if your default branch is different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:ci # Allow running in github workflow CI testing

      - name: Build Angular App
        run: npm run build -- --base-href="/testci/"

      - name: Deploy to GitHub Pages In master
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master # this branch name is create automatic in github it can be any branch name
          folder: dist/test1/browser
          clean: true
          force: true
